repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.9
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/ddanier/sub-pre-commit.git
  rev: v4.5.1
  hooks:
    - id: sub-pre-commit
      name: npm precommit action
      args: ["-p", "game_anywhere/client"]
      files: ^game_anywhere/client/.*
