[project]
name = "game_anywhere_examples"
dependencies = ["game_anywhere"]
version = "0.1"
authors = [
    {name = "Pierre Ballif", email = "pierre@ballif.eu"},
]
description = "Example games for the game_anywhere framework."

[project.optional-dependencies]
chess = ["chess"]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project.entry-points."game_anywhere.games"]
chess = "game_anywhere_examples.chess_wrapper:Chess"
tic_tac_toe = "game_anywhere_examples.tic_tac_toe:TicTacToe"
poker = "game_anywhere_examples.poker:Poker"
werewolves = "game_anywhere_examples.werewolves:Werewolves"
hanabi = "game_anywhere_examples.hanabi:Hanabi"
skull = "game_anywhere_examples.skull:Skull"

[tool.setuptools.package-data]
game_anywhere_examples = ["*/assets/**"]
